package org.lw.vms.enums;

public enum VehicleBrand {
    BMW, AUDI, MERCEDES, VOLKSWAGEN, TOYOTA, HONDA, FORD, NISSAN, HYUNDAI, KIA, JEEP, LANDROVER, TESLA, VOLVO, FIAT, PEUGEOT, CITROEN, OPEL, SKODA, MAZDA, SUZUKI
}
