spring:
  datasource:
    url: jdbc:mysql://localhost:3306/databasedesignproject?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver



server:
  port: 10086

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true

