spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vms?useSSL=false&serverTimezone=UTC
    username: root
    password: LHX!316696
    driver-class-name: com.mysql.cj.jdbc.Driver



server:
  port: 10086

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true

jwt:
  expiration: 3600000
  secret: yourVerySecureRandomBase64EncodedSecretKeyWhichShouldBeLongAndComplexAndUnique1234567890ABCDEF

